apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # labels of deployment resource
  labels:
    app: frontend
    tier: frontend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        project: expense
    spec:
      containers:
        - name: frontend
          image: peddireddylokesh/frontend:1.2.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:                 # this is all internal to the cluster
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: frontend
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:897729141306:certificate/135abcaf-dbd7-4da2-be49-3e1ff5fc4188
    alb.ingress.kubernetes.io/group: peddireddylokesh
spec:
  ingressClassName: alb
  rules:
  - host: "expense.lokeshportfo.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: 80
---